<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{487ac2db-d967-499e-ac9e-fd5c6a60eb36}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Hethong : FB_System;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Hethong();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>