<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{df3f6be4-87c9-4c81-9aa5-3c217e2e5fbf}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbReader : FB_RRU7001;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbReader();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>